import { motion } from 'framer-motion'
import PageLayout from '../components/PageLayout'

const sections = [
  { title: 'Information We Collect', body: 'We collect information you provide directly (name, email, company), information generated by your use of the Service (usage logs, agent configurations, workflow data), and technical information (IP address, browser type, device identifiers). We do not sell your personal data to third parties.' },
  { title: 'How We Use Your Information', body: 'We use your information to provide and improve the Service, send transactional and product communications, respond to support requests, detect and prevent fraud or security incidents, and comply with legal obligations. We will not use your data to train third-party AI models without your explicit consent.' },
  { title: 'Data Sharing', body: 'We share your information with trusted service providers (cloud infrastructure, payment processing, analytics) who are contractually bound to protect your data. We may share information when required by law, to protect Gridd\'s rights, or in connection with a merger or acquisition. We will notify you of any such changes where required.' },
  { title: 'Data Retention', body: 'We retain your personal data for as long as your account is active or as needed to provide the Service. You may request deletion of your data at any time. Some data may be retained for legal compliance or fraud prevention purposes for up to 7 years after account closure.' },
  { title: 'Your Rights', body: 'Depending on your location, you may have the right to access, correct, or delete your personal data; to restrict or object to processing; to data portability; and to withdraw consent. EU/EEA residents have rights under GDPR. California residents have rights under CCPA. Contact privacy@gridd.ai to exercise your rights.' },
  { title: 'Cookies', body: 'We use essential cookies for authentication and security, functional cookies to remember your preferences, and analytics cookies to understand usage patterns. You can manage cookie preferences in your browser settings or through our cookie consent banner. Rejecting non-essential cookies will not affect core functionality.' },
  { title: 'Security', body: 'We implement industry-standard security measures including encryption in transit (TLS 1.3) and at rest (AES-256), SOC 2 Type II compliant infrastructure, regular penetration testing, and access controls. No system is 100% secure; please report vulnerabilities to security@gridd.ai.' },
  { title: 'Changes to This Policy', body: 'We may update this Privacy Policy from time to time. We will notify you of material changes via email or in-app notification at least 30 days before they take effect. Continued use of the Service after changes take effect constitutes acceptance of the revised policy.' },
]

export default function Privacy() {
  return (
    <PageLayout>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-12">
          <span className="inline-block px-3 py-1 rounded-full text-xs font-semibold text-white/50 bg-white/[0.06] border border-white/[0.08] mb-4">Legal</span>
          <h1 className="text-4xl sm:text-5xl font-black tracking-tight mb-4">Privacy Policy</h1>
          <p className="text-sm text-white/35">Last updated: June 1, 2025 · Applies to all Gridd services</p>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.15 }} className="glass rounded-2xl p-8 border border-white/[0.06] space-y-8">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-base font-bold text-white mb-3">{s.title}</h2>
              <p className="text-sm text-white/50 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </motion.div>

        <p className="text-center text-xs text-white/25 mt-8">
          Privacy questions?{' '}
          <a href="mailto:privacy@gridd.ai" className="text-indigo-400 hover:text-indigo-300 transition-colors">privacy@gridd.ai</a>
        </p>
      </div>
    </PageLayout>
  )
}
